# Generated by Django 3.2.4 on 2021-06-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_participant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferred_role',
            field=models.CharField(choices=[('Teaching', 'TEACHING'), ('Teaching Assistant', 'TEACHING_ASSISTANT'), ('IT', 'IT')], max_length=18),
        ),
    ]
