# Generated by Django 3.2.4 on 2021-06-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210611_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferred_role',
            field=models.CharField(choices=[('Teaching', 'TEACHING'), ('Teaching Assistant', 'TEACHING ASSISTANT'), ('IT', 'IT')], max_length=18),
        ),
    ]
