# Generated by Django 3.2.13 on 2022-06-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220601_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='alternate_contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='primary_contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='whatsApp_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
