# Generated by Django 3.2.15 on 2022-08-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_volunteer_preferred_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantPickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_1", models.DateTimeField(blank=True, null=True)),
                ("day_2", models.DateTimeField(blank=True, null=True)),
                ("day_3", models.DateTimeField(blank=True, null=True)),
                ("day_4", models.DateTimeField(blank=True, null=True)),
                ("day_5", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParticipantAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_1", models.DateTimeField(blank=True, null=True)),
                ("day_2", models.DateTimeField(blank=True, null=True)),
                ("day_3", models.DateTimeField(blank=True, null=True)),
                ("day_4", models.DateTimeField(blank=True, null=True)),
                ("day_5", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
