# Generated by Django 3.2.15 on 2022-08-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220828_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupcode',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.participant'),
        ),
    ]
