# Generated by Django 2.2.6 on 2019-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_church'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=12)),
            ],
        ),
    ]
