# Generated by Django 2.2.6 on 2019-11-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pickupperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('primary_contact_no', models.CharField(max_length=12)),
                ('alternate_contact_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
