# Generated by Django 2.2.6 on 2019-11-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupperson',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
