# Generated by Django 2.2.6 on 2019-11-02 20:56

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191102_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(core.models.GenderChoice('Male'), 'Male'), (core.models.GenderChoice('Female'), 'Female')], max_length=6)),
                ('medical_info', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Church')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Grade')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Parent')),
                ('pickup_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PickupPerson')),
            ],
        ),
    ]
