# Generated by Django 2.2.6 on 2019-11-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191113_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
