# Generated by Django 2.2.6 on 2019-11-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_volunteer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
