# Generated by Django 2.2.6 on 2019-11-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('role', models.CharField(max_length=12)),
                ('preferred_class', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('previous_volunteer', models.BooleanField(default=False)),
                ('previous_site', models.CharField(blank=True, max_length=100)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Church')),
            ],
        ),
    ]
