# Generated by Django 2.2.6 on 2020-04-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Tsatsu', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Adogla-Bessa', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferred_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Grade'),
        ),
    ]
