# Generated by Django 2.2.6 on 2020-04-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200411_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pickup_person',
        ),
        migrations.AddField(
            model_name='participant',
            name='alternate_contact_no',
            field=models.CharField(default='0244123456', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='parent_name',
            field=models.CharField(default='Aforo Asomaning', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='pickup_person_contact_no',
            field=models.CharField(default='0244123456', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='pickup_person_name',
            field=models.CharField(default='Aforo Asomaning', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='primary_contact_no',
            field=models.CharField(default='0244123456', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='whatsApp_no',
            field=models.CharField(default='0244123456', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='church',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='church',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferred_class',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='PickupPerson',
        ),
    ]
