# Generated by Django 2.2.6 on 2020-04-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200412_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='church',
            field=models.CharField(max_length=150),
        ),
    ]
