# Generated by Django 2.2.6 on 2020-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200412_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='church',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pickup_person_name',
            field=models.CharField(max_length=100),
        ),
    ]
