# Generated by Django 2.2.12 on 2020-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200412_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='whatsApp_no',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='whatsApp_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
