# Generated by Django 2.2.12 on 2020-04-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200413_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='role',
            new_name='preferred_role',
        ),
    ]
