# Generated by Django 2.2.12 on 2020-04-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200413_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=5, max_length=2),
            preserve_default=False,
        ),
    ]
