# Generated by Django 2.2.14 on 2020-07-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200425_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='medical_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pickup_person_contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pickup_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
