# Generated by Django 2.2.14 on 2020-07-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200710_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='whatsApp_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
